name: Bump Script Version

on:
  push:
  pull_request:

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      # Check if ngrok-plex.py has been modified since the last commit
      - name: Update Script Version
        id: update-script
        env:
          GIT_AUTH: ${{ secrets.GIT_AUTH }}
        run: |
          if ! git diff HEAD~1 --name-only | grep -q "ngrok-plex.py"; then
            echo "No changes to ngrok-plex.py since last commit"
            exit 0
          else
            echo "ngrok-plex.py file has been modified"
            # Get the previous SCRIPT_VERSION from the last commit
            PREVIOUS_SCRIPT_VERSION=$(git show HEAD~:ngrok-plex.py | grep "SCRIPT_VERSION = " | cut -d "=" -f 2 | tr -d " '\"")

            # Get the current SCRIPT_VERSION from ngrok-plex.py
            SCRIPT_VERSION=$(grep "SCRIPT_VERSION = " ngrok-plex.py | cut -d "=" -f 2 | tr -d " '\"")

            # Check if the SCRIPT_VERSION has been manually updated
            if [[ "$SCRIPT_VERSION" != "$PREVIOUS_SCRIPT_VERSION" ]]; then
              echo "SCRIPT_VERSION has been manually updated"
              exit 0
            else
              echo 'SCRIPT_VERSION has NOT been manually updated'
              # Increment the SCRIPT_VERSION by 0.1
              NEW_SCRIPT_VERSION=$(awk -v x=$SCRIPT_VERSION 'BEGIN { printf "%.1f", x+0.1 }')

              # Update the SCRIPT_VERSION in ngrok-plex.py
              sed -i "s/$SCRIPT_VERSION/$NEW_SCRIPT_VERSION/g" ngrok-plex.py
              if [[ $(git status) == *"nothing to commit, working tree clean"* ]]; then
              echo "Nothing to commit, working tree clean"
              exit 0
              fi
              git config user.name "GitHub Actions"
              git config user.email "actions@github.com"
              git remote set-url origin https://${{ secrets.GIT_AUTH }}@github.com/origamiofficial/docker-ngrok-plex.git
              git add ngrok-plex.py
              git commit -m "Bump Script Version"
              git push
            fi
          fi
